module Raysetta
  module Background
    class Base < EntityBase
      def sample: (Ray r) -> Vec3

      def export: () -> Hash[Symbol, untyped]
      def textures: () -> Array[Texture::Base]
      def images: () -> Array[Image]
    end
  end
end
