module Raysetta
  module Material
    class Base < EntityBase
      def emitted: (Vec2 uv, Vec3 point) -> Color
      def scatter: (Ray r_in, Hit rec) -> Scatter?

      def export: () -> Hash[Symbol, untyped]
      def textures: () -> Array[Texture::Base]
    end
  end
end
