module Raysetta
  module Material
    class DiffuseLight < Base
      attr_accessor texture: Texture::Base

      def initialize: (Texture::Base texture) -> void
      def self.solid: (Vec3 albedo) -> instance

      def textures: () -> [Texture::Base]
    end
  end
end
