module Parallel
  def self.map: [I, O] (Array[I], in_threads: Integer, ?finish: Proc) { (I) -> O } -> Array[O]
              | [I, O] (Array[I], in_processes: Integer, ?finish: Proc) { (I) -> O } -> Array[O]
              | [I] (Array[I], in_ractors: Integer, ractor: [Class, Symbol], ?finish: Proc) -> Array[untyped]
end
