module Raysetta
  class Color < Vec3
    def r: () -> Float
    def g: () -> Float
    def b: () -> Float

    def r=: (Float v) -> Float
    def g=: (Float v) -> Float
    def b=: (Float v) -> Float

    def multiply: (Color v) -> self
    def times: (Color v) -> Color

    def to_pixel: () -> [Integer, Integer, Integer]
  end
end
