module Raysetta
  module Util
    def self.degrees_to_radians: (Float degrees) -> Float

    # Returns a random real in [min,max).
    def self.random: (Float min, Float max) -> Float

    def self.linear_to_gamma: (Float linear_component) -> Float
    def self.gamma_to_linear: (Float gamma_component, ?Float gamma) -> Float

    def self.sphere_uv: (Vec3 point) -> Vec2
  end
end
