module Raysetta
  class Vec
    @e: Array[Float]

    def self.dimensions: () -> Integer

    def initialize: (*Float args) -> void

    def self.repeat: (Float t) -> instance

    def to_a: () -> Array[Float]
    alias to_ary to_a

    def -@: () -> instance

    def []: (Integer i) -> Float
    def []=: (Integer i, Float v) -> Float

    def +: (Vec v) -> instance
    def -: (Vec v) -> instance
    def *: (Float t) -> instance
    def /: (Float t) -> instance

    def add: (Vec v) -> self
    def sub: (Vec v) -> self
    def mul: (Float t) -> self
    def div: (Float t) -> self

    def neg: () -> self

    def length: () -> Float
    def length_squared: () -> Float

    def dot: (Vec v) -> Float
    def unit: () -> instance
    def normalize: () -> self

    def dup: () -> instance

    def abs!: () -> self
    def abs: () -> instance

    def smoothstep!: () -> self
    def smoothstep: () -> instance

    EPSILON: Float

    # Return true if the vector is close to zero in all dimensions.
    def zero?: () -> bool

    def to_s: () -> String
    def ==: (untyped v) -> bool
    alias eql? ==
    def hash: () -> Integer

    def self.random: (?Float min, ?Float max) -> instance

    attr_reader e: Array[Float]
  end
end
