# frozen_string_literal: true

module Raysetta
  class Error < StandardError; end
end

require_relative "raysetta/version"
require_relative "raysetta/util"
require_relative "raysetta/vec2"
require_relative "raysetta/vec3"
require_relative "raysetta/ray"
require_relative "raysetta/interval"
require_relative "raysetta/aabb"
require_relative "raysetta/hit"
require_relative "raysetta/scatter"
require_relative "raysetta/entity_base"
require_relative "raysetta/image"
require_relative "raysetta/perlin"
require_relative "raysetta/object/base"
require_relative "raysetta/object/bvh"
require_relative "raysetta/object/group"
require_relative "raysetta/object/sphere"
require_relative "raysetta/object/moving_sphere"
require_relative "raysetta/object/quad"
require_relative "raysetta/object/tri"
require_relative "raysetta/object/box"
require_relative "raysetta/material/base"
require_relative "raysetta/material/lambertian"
require_relative "raysetta/material/metal"
require_relative "raysetta/material/dielectric"
require_relative "raysetta/material/diffuse_light"
require_relative "raysetta/texture/base"
require_relative "raysetta/texture/solid_color"
require_relative "raysetta/texture/checker"
require_relative "raysetta/texture/image"
require_relative "raysetta/texture/noise"
require_relative "raysetta/background/base"
require_relative "raysetta/background/solid"
require_relative "raysetta/background/gradient"
require_relative "raysetta/background/sphere_map"
require_relative "raysetta/background/cube_map"
require_relative "raysetta/camera"
require_relative "raysetta/scene"
require_relative "raysetta/tracer"
