module Raysetta
  module Texture
    class Base < EntityBase
      def sample: (Vec2 uv, Vec3 point) -> Vec3

      def export: () -> Hash[Symbol, untyped]
      def images: () -> Array[Image]
      def noises: () -> Array[Perlin]
    end
  end
end
