module Raysetta
  module Texture
    class Checker < Base
      attr_accessor inv_scale: Float
      attr_accessor even: Texture::Base
      attr_accessor odd: Texture::Base

      def initialize: (Float scale, Texture::Base even, Texture::Base odd) -> void
      def self.solid: (Float scale, Color even, Color odd) -> instance

      def scale=: (Float scale) -> Float
      def scale: () -> Float
    end
  end
end
